spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    dialect: org.hibernate.dialect.MySQL8Dialect
    url: jdbc:mysql://localhost:3306/blogengine?serverTimezone=UTC
    username: root
    password: testtest
  jpa:
    hibernate.ddl-auto: none
    properties:
      hibernate.show_sql: false

blog:
  title: DevPub
  subtitle: Рассказы разработчиков
  phone: +7 903 666-44-55
  email: mail@mail.ru
  copyright: Дмитрий Сергеев
  copyrightFrom: 2005