spring:

  datasource:
    driverClassName: com.mysql.jdbc.Driver
    dialect: org.hibernate.dialect.MySQL8Dialect
    url: jdbc:mysql://localhost:3306/blogengine?serverTimezone=UTC
    username: root
    password: testtest

  jpa:
    hibernate.ddl-auto: none
    properties:
      hibernate.show_sql: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: box4andronova@gmail.com
    password: Ukflbjkec45
    protocol: smtp
    tls: true
    properties.mail.smtp:
      auth: true
      starttls.enable: true
      ssl.trust: smtp.gmail.com

blog:
  title: DevPub
  subtitle: Рассказы разработчиков
  phone: +7 902 172-58-36
  email: box4andronova@gmail.com
  copyright: Татьяна Андронова
  copyrightFrom: 2021
  minWeight: 0.2
  minuteLifeCaptcha: 60