spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    dialect: org.hibernate.dialect.MySQL8Dialect
    url: jdbc:mysql://localhost:3306/blogengine?serverTimezone=UTC
    username: root
    password: testtest
  jpa:
    hibernate.ddl-auto: none
    properties:
      hibernate.show_sql: false
  mail:
    protocol: smtps
    host: smtp.yandex.ru
    port: 465
    username: box4andronova
    password: Ukflbjkec45

blog:
  title: DevPub
  subtitle: Рассказы разработчиков
  phone: +7 902 172-58-36
  email: box4andronova@yandex.ru
  copyright: Татьяна Андронова
  copyrightFrom: 2021
  minWeight: 0.2
  minuteLifeCaptcha: 60