spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    dialect: org.hibernate.dialect.MySQL8Dialect
    url: jdbc:mysql://localhost:3306/blogengine?serverTimezone=UTC
    username: root
    password: testtest
  jpa:
    hibernate.ddl-auto: none
    properties:
      hibernate.show_sql: false

blog:
  title: DevPub
  subtitle: Рассказы разработчиков
  phone: +7 902 172-58-36
  email: kirangarsk@mail.ru
  copyright: Татьяна Андронова
  copyrightFrom: 2021
  minWeight: 0.2
  minuteLifeCaptcha: 60